// Portfolio Data Configuration
// Edit this file to customize your portfolio content

export const siteConfig = {
  name: "Yegor Lushpin",
  title: "Electrical Engineering Student",
  subtitle: "University of Cincinnati | TREW Automation Co-op '26",
  description: "Electrical Engineering student passionate about embedded systems, battery technology, and renewable energy. Accepted 1st Co-op at TREW Automation (Fall 2026) | Seeking 2nd Co-op Summer 2027.",
  email: "lushpiev@mail.uc.edu",
  phone: "(859) 786-2491",
  location: "Cincinnati, Ohio",
  availability: "1st Co-op: TREW Automation, Fall 2026 | Seeking 2nd Co-op Summer 2027",
  social: {
    linkedin: "https://www.linkedin.com/in/yegorlushpin",
    github: "https://github.com/egrqwertyuio",
    twitter: "",
  },
  resumeUrl: "/resume.pdf",
};

export const aboutData = {
  bio: `My name is Yegor Lushpin, I am an Electrical Engineering student at the University of Cincinnati with hands-on experience in high-voltage battery systems, iOS development, and scientific computing.
  I have contributed to a NASA-supported citizen science app for photographing solar eclipses and am currently supporting the design and integration of high-voltage battery systems for a Formula SAE electric race car. 
  
  I am passionate about embedded systems, battery technology, and solving problems in general. However I am most passionate about making a change in this world, my dream job is in Renewable and Clean Energy Systems and adjacent industries. 

  I have accepted my 1st co-op position at TREW Automation in West Chester, OH starting Fall 2026, focused on electrical drawings and design. I am actively seeking a 2nd co-op for Summer 2027.
  
  I also love my dog, Gosha, he is a 2 years old squishy pug and he is the best. P.S. there is an easter egg somewhere on my page about him, can you find it?`,
  specialties: [
    "Battery Systems & HV Safety",
    "iOS Development (Swift)",
    "MATLAB Modeling",
    "PCB Design (KiCad)",
    "Embedded Systems",
    "Test & Validation",
  ],
  education: [
    {
      degree: "B.S. in Electrical Engineering",
      school: "University of Cincinnati",
      year: "Expected May 2030",
      description: "GPA: 2.91",
    },
    {
      degree: "High School Diploma, Summa Cum Laude",
      school: "Campbell County High School, Alexandria, KY",
      year: "Jun 2025",
      description: "GPA: 4.00",
    },
  ],
  certifications: [
    "Microsoft Office (Word, Excel, PowerPoint) - May 2023",
  ],
};

export const skillsData = {
  hardware: [
    { name: "Oscilloscope", level: 50 },
    { name: "Multimeter", level: 60 },
    { name: "Soldering", level: 80 },
    { name: "KiCad", level: 50 },
    { name: "Battery Systems", level: 50 },
    { name: "HV Safety", level: 50 },
  ],
  embedded: [
    { name: "C/C++", level: 70 },
    { name: "Python", level: 80 },
    { name: "Java", level: 80 },
    { name: "Swift", level: 70 },
    { name: "MATLAB", level: 75 },
    { name: "LabVIEW", level: 60 },
  ],
  tools: [
    { name: "Visual Studio Code", level: 80 },
    { name: "Git", level: 80 },
    { name: "Linux", level: 60 },
    { name: "Microsoft Office", level: 95 },
    { name: "Seimens NX", level: 75 },
    { name: "Simulink", level: 60 },
  ],
  software: [
    { name: "Python", level: 80 },
    { name: "Git", level: 70 },
    { name: "Linux", level: 60 },
    { name: "Swift (iOS)", level: 60 },
    { name: "Java", level: 80 },
    { name: "C/C++", level: 70 },
  ],
};

export const projectsData = [
  {
    id: 1,
    title: "Busbar Design, Testing & HV Accumulator",
    description: "Drafted busbar and fusible link drawings for efficient manufacturing of critical overcurrent protection. Validated fusible link dimensions using oscilloscope measurements and supported HV accumulator integration for the Formula SAE electric race car.",
    image: "/images/projects/BearcatsEV/BusBars/image0.jpeg",
    gallery: [
      { type: "image" as const, src: "/images/projects/BearcatsEV/BusBars/image0.jpeg", alt: "Busbar assembly" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/BusBars/image1.jpeg", alt: "Busbar testing" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/BusBars/image2.jpeg", alt: "Fusible link" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/BusBars/image3.jpeg", alt: "HV components" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/BusBars/image4.jpeg", alt: "Assembly detail" },
      { type: "video" as const, src: "/images/projects/BearcatsEV/BusBars/linktesting.mov", alt: "Link testing video" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/BusBars/BER_A1_BusBars_Nickel_Copper-images-0.jpg", alt: "Busbar drawing page 1" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/BusBars/BER_A1_BusBars_Nickel_Copper-images-1.jpg", alt: "Busbar drawing page 2" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/BusBars/Battery_Diagram.jpg", alt: "Battery diagram" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/3dModels/FusableLink_testing_strips.png", alt: "Fusible link testing strips" },
    ],
    technologies: ["HV Systems", "FSAE", "Oscilloscope", "CAD", "Safety Systems"],
    category: "Hardware",
    github: "",
    demo: "",
    featured: true,
  },
  {
    id: 2,
    title: "SunSketcher - Eclipse Simulation",
    description: "Modeled eclipse simulations based on collected data in MATLAB in collaboration with NASA engineers and leading heliophysicists in the field.",
    image: "/images/projects/SunSketcher/MatLabSunSketcherGraph1.png",
    gallery: [
      { type: "image" as const, src: "/images/projects/SunSketcher/MatLabSunSketcherGraph1.png", alt: "Eclipse simulation graph 1" },
      { type: "image" as const, src: "/images/projects/SunSketcher/MatLabSunSketcherGraph2.png", alt: "Eclipse simulation graph 2" },
      { type: "image" as const, src: "/images/projects/SunSketcher/MatLabSunSketcherGraph3.png", alt: "Eclipse simulation graph 3" },
      { type: "image" as const, src: "/images/projects/SunSketcher/MatLabSunSketcherMoonGraph.png", alt: "Moon simulation graph" },
    ],
    technologies: ["MATLAB", "Data Analysis", "NASA", "Scientific Computing"],
    category: "Software",
    github: "",
    demo: "",
    featured: true,
  },
  {
    id: 3,
    title: "SunSketcher iOS App",
    description: "NASA-supported citizen science smartphone app that lets anyone in the path of totality automatically photograph total solar eclipses, contributing precisely timed images that help researchers measure the Sun's size, shape, and internal dynamics.",
    image: "/images/projects/SunSketcher/IOS Development.jpeg",
    gallery: [
      { type: "image" as const, src: "/images/projects/SunSketcher/IOS Development.jpeg", alt: "iOS Development" },
    ],
    technologies: ["Swift", "iOS", "NASA", "Server Integration", "Encryption"],
    category: "Software",
    github: "",
    demo: "",
    featured: true,
  },
  {
    id: 4,
    title: "3D CAD Modeling - Battery Components",
    description: "Designed 3D models for battery pack components including spacers, washers, and HVIL receptacles for the Formula SAE electric race car.",
    image: "/images/projects/BearcatsEV/3dModels/ModuleSpacerBlock_4Assembly_dwg1.png",
    gallery: [
      { type: "image" as const, src: "/images/projects/BearcatsEV/BusBars/BER_A1_BusBars_Nickel_Copper-images-0.jpg", alt: "Busbar drawing page 1" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/BusBars/BER_A1_BusBars_Nickel_Copper-images-1.jpg", alt: "Busbar drawing page 2" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/3dModels/ModuleSpacerBlock_4Assembly_dwg1.png", alt: "Module spacer block assembly" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/3dModels/HVIL_recepticle_dwg1.png", alt: "HVIL receptacle drawing" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/3dModels/Spacers_4Lid_Assembly_dwg1.png", alt: "Spacers lid assembly" },
      { type: "image" as const, src: "/images/projects/BearcatsEV/3dModels/bbb_washer_dwg1.png", alt: "BBB washer drawing" },
    ],
    technologies: ["CAD", "3D Modeling", "FSAE", "Manufacturing"],
    category: "Hardware",
    github: "",
    demo: "",
    featured: true,
  },
  {
    id: 5,
    title: "Heart PCB Design",
    description: "Custom heart-shaped PCB with integrated LED lighting — designed in KiCad, fabricated externally, and hand-soldered. A practical exercise covering the full PCB workflow from schematic capture to assembled board.",
    image: "/images/projects/Personal Projects/heart pcb/heart_pcb.png",
    gallery: [
      { type: "image" as const, src: "/images/projects/Personal Projects/heart pcb/heart_pcb.png", alt: "Heart PCB render" },
      { type: "video" as const, src: "/images/projects/Personal Projects/heart pcb/heartpcb.MOV", alt: "Heart PCB demo" },
      { type: "video" as const, src: "/images/projects/Personal Projects/heart pcb/Video_1.mov", alt: "Heart PCB video" },
      { type: "image" as const, src: "/images/projects/Personal Projects/heart pcb/heartpcb.jpg", alt: "Heart PCB schematic" },
      { type: "image" as const, src: "/images/projects/Personal Projects/heart pcb/Screenshot 2026-02-07 003930.png", alt: "Heart PCB screenshot" },
    ],
    technologies: ["KiCad", "PCB Design", "Soldering", "LED"],
    category: "Personal",
    github: "",
    demo: "",
    featured: false,
    details: {
      objective: "Design and fabricate a custom heart-shaped PCB as a decorative LED piece. Primary goal was hands-on practice with the full PCB pipeline in KiCad — from schematic capture and layout to Gerber export, external fabrication, and SMD hand-soldering.",
      bom: [
        { item: "Custom PCB — JLCPCB (5-pack)", qty: "1 order", unitCost: "$5.00" },
        { item: "WS2812B Addressable RGB LEDs", qty: "~20", unitCost: "$4.00" },
        { item: "100nF Decoupling Capacitors (SMD 0805)", qty: "~20", unitCost: "$1.00" },
        { item: "USB Type-A Power Connector", qty: "1", unitCost: "$0.50" },
        { item: "PCB Standoffs", qty: "4", unitCost: "$1.00" },
      ],
      totalCost: "~$11.50",
      architecture: "Single-layer heart-shaped PCB. WS2812B LEDs arranged along the heart outline with a daisy-chained data line. 5V USB power input with 100nF bypass capacitors on every LED for supply-rail stability. Data signal driven directly from a microcontroller pin.",
      process: [
        "Sketched heart silkscreen outline in KiCad PCB editor and placed LED footprints along the path",
        "Routed data chain and 5V/GND power rails; added bypass capacitors at each LED",
        "Ran DRC — zero errors before exporting Gerbers",
        "Ordered from JLCPCB (5-pack, ~1-week lead time)",
        "Hand-soldered all SMD components under magnification",
        "Verified power continuity and data chain, then tested LED animation sequences",
      ],
      results: "Fully functional LED heart with animated lighting patterns. Successfully demonstrated the end-to-end KiCad PCB workflow and SMD soldering technique.",
    },
  },
  {
    id: 6,
    title: "Cyber Glass",
    description: "Cyberpunk-inspired AR wearable — a heads-up display built into a glasses form factor using an ESP32-CAM and a compact OLED. Early prototype and concept stage.",
    image: "/images/projects/Personal Projects/CyberGlass/image0.jpeg",
    gallery: [
      { type: "image" as const, src: "/images/projects/Personal Projects/CyberGlass/image0.jpeg", alt: "Cyber Glass prototype" },
    ],
    technologies: ["ESP32-S3", "ESP32-CAM", "OLED Display", "LiPo", "Wearables"],
    category: "Personal",
    github: "",
    demo: "",
    featured: false,
    inProgress: true,
    details: {
      objective: "Design a cyberpunk-inspired AR wearable — a compact heads-up display embedded in a glasses frame. Inspired by Cyberpunk 2077 aesthetics with practical smart-glass functionality: real-time overlays, camera input, and wireless connectivity.",
      bom: [
        { item: "ESP32-S3 (main MCU)", qty: "1", unitCost: "~$8.00" },
        { item: "ESP32-CAM AI-Thinker (vision)", qty: "1", unitCost: "~$7.99" },
        { item: "0.49″ Transparent OLED / Micro Display", qty: "1", unitCost: "~$15–30" },
        { item: "LiPo Battery 300–500 mAh", qty: "1", unitCost: "~$5.00" },
        { item: "TP4056 Charging + Protection Module", qty: "1", unitCost: "~$1.00" },
        { item: "MPU-6050 IMU (gesture input)", qty: "1", unitCost: "~$2.00" },
        { item: "INMP441 MEMS Microphone", qty: "1", unitCost: "~$3.00" },
        { item: "3D-Printed Glasses Frame (PLA)", qty: "1", unitCost: "~$3.00" },
      ],
      totalCost: "~$45–60 estimated",
      brainstorm: [
        "Transparent OLED overlay for displaying time, notifications, and sensor readings without blocking vision",
        "ESP32-CAM for real-time object detection or face recognition in-frame",
        "IMU-based head-gesture control to navigate on-screen menus",
        "BLE pairing to phone for notification mirroring and remote control",
        "INMP441 microphone for wake-word detection and voice commands",
        "Custom 3D-printed frame designed to conceal all components and wiring",
        "USB-C charging via TP4056 module with battery protection circuit",
      ],
    },
  },
  {
    id: 7,
    title: "6DoF Robotic Arm",
    description: "6 degrees-of-freedom robotic arm with a fully 3D-printed structure and servo-driven joints. Capable of autonomous pick-and-place operations with a programmable control system.",
    image: "/images/projects/Personal Projects/6DoF Robot/IMG_2568.jpeg",
    gallery: [
      { type: "image" as const, src: "/images/projects/Personal Projects/6DoF Robot/IMG_2568.jpeg", alt: "6DoF Robot" },
      { type: "video" as const, src: "/images/projects/Personal Projects/6DoF Robot/Video.mov", alt: "6DoF Robot demo" },
    ],
    technologies: ["Arduino", "Servo Control", "3D Printing", "Robotics", "PCA9685"],
    category: "Personal",
    github: "",
    demo: "",
    featured: false,
    inProgress: true,
    details: {
      objective: "Build a 6 degrees-of-freedom robotic arm capable of autonomous pick-and-place operations. Entirely 3D-printed structure with servo-driven joints and a programmable control system targeting inverse kinematics and teach-and-playback operation.",
      bom: [
        { item: "MG996R Metal Gear Servo Motors", qty: "6", unitCost: "~$18.00 total" },
        { item: "Arduino Mega 2560", qty: "1", unitCost: "~$12.00" },
        { item: "PCA9685 16-Ch PWM Servo Driver", qty: "1", unitCost: "~$4.99" },
        { item: "5V 5A DC Power Supply", qty: "1", unitCost: "~$10.00" },
        { item: "PLA Filament", qty: "~500g", unitCost: "~$10.00" },
        { item: "M3 Screw & Hardware Kit", qty: "1 set", unitCost: "~$5.00" },
        { item: "Buck Converter (12V → 5V logic)", qty: "1", unitCost: "~$2.00" },
      ],
      totalCost: "~$62",
      brainstorm: [
        "Forward and inverse kinematics for precise end-effector position control",
        "Teach-and-playback mode: manually position the arm, record joint angles, replay the sequence",
        "Computer vision integration (webcam + OpenCV) for object detection and autonomous grasping",
        "Custom web UI or PS4 controller for manual joint-by-joint operation",
        "G-code compatible command interface for CNC-style programmatic paths",
        "End-effector options: gripper, suction cup, or pen for drawing",
      ],
    },
  },
  {
    id: 8,
    title: "Jarvis AI Assistant",
    description: "Iron Man-inspired personal AI assistant. Wake-word activated, speech-to-text input, LLM-backed reasoning, and synthesized voice responses — running locally on a PC.",
    image: "/images/projects/Personal Projects/jarvis/image0.jpeg",
    gallery: [
      { type: "image" as const, src: "/images/projects/Personal Projects/jarvis/image0.jpeg", alt: "Jarvis AI Assistant" },
      { type: "video" as const, src: "/images/projects/Personal Projects/jarvis/Video.mov", alt: "Jarvis demo" },
    ],
    technologies: ["Python", "Speech Recognition", "LLM API", "TTS", "NLP"],
    category: "Personal",
    github: "",
    demo: "",
    featured: false,
    details: {
      objective: "Build a voice-activated personal AI assistant inspired by Iron Man's J.A.R.V.I.S. The system listens for a wake word, transcribes speech, processes natural language commands through an LLM, and responds with a synthesized voice — all running locally.",
      bom: [
        { item: "PC / Laptop (existing hardware)", qty: "1", unitCost: "$0" },
        { item: "USB Microphone", qty: "1", unitCost: "~$10.00" },
        { item: "Speaker / Headphone Output", qty: "1", unitCost: "~$15.00" },
        { item: "Python Libraries (all open-source)", qty: "—", unitCost: "$0" },
        { item: "LLM API Access (e.g., OpenAI / Anthropic)", qty: "—", unitCost: "Pay-per-use" },
      ],
      totalCost: "~$25 hardware + API usage",
      architecture: "Pipeline: wake-word detection (Porcupine / custom hotword engine) → SpeechRecognition (Google STT) for transcription → LLM API for intent parsing and response generation → pyttsx3 / ElevenLabs TTS for voice output. Modular Python architecture with pluggable skill modules (weather, system control, web search, timers).",
      process: [
        "Implemented hotword detection to trigger the listening pipeline without always-on STT",
        "Integrated Google Speech Recognition API for accurate real-time transcription",
        "Connected LLM backend to process intent and generate contextual responses",
        "Built TTS pipeline with customized voice for the JARVIS persona",
        "Added modular skill system: weather lookup, time/date, web search, system commands",
        "Packaged as a background service with CLI interface",
      ],
      results: "Functional voice assistant capable of responding to natural language queries, answering questions via LLM, and executing system-level commands via voice. Continuous improvement ongoing.",
    },
  },
  {
    id: 9,
    title: "PMR Robot",
    description: "ENED 1002c class project — a LEGO Mindstorms EV3 Prototype Mover Robot (PMR) that autonomously follows a closed-loop line path, picks up bins of shredded material, classifies them by weight, and delivers them to the correct drop-off location.",
    image: "/images/projects/PMR/Subtask2Finalpicture.jpg",
    gallery: [
      { type: "image" as const, src: "/images/projects/PMR/Subtask2Finalpicture.jpg", alt: "PMR Robot final" },
      { type: "image" as const, src: "/images/projects/PMR/Subtask2Finalpicture2.jpg", alt: "PMR Robot final 2" },
      { type: "image" as const, src: "/images/projects/PMR/Subtask2picture.jpg", alt: "PMR Robot subtask 2" },
      { type: "image" as const, src: "/images/projects/PMR/Subtask1picture.png", alt: "PMR Robot subtask 1" },
      { type: "image" as const, src: "/images/projects/PMR/Subtask1picture2.png", alt: "PMR Robot subtask 1 alt" },
      { type: "image" as const, src: "/images/projects/PMR/NewLiftMechanism.jpg", alt: "New lift mechanism" },
      { type: "image" as const, src: "/images/projects/PMR/DesignProcess.jpg", alt: "Design process" },
      { type: "image" as const, src: "/images/projects/PMR/DesignProcess2.jpg", alt: "Design process 2" },
      { type: "image" as const, src: "/images/projects/PMR/DesignProcess3.jpg", alt: "Design process 3" },
    ],
    technologies: ["LEGO Mindstorms EV3", "LabVIEW", "Robotics", "Autonomous Systems"],
    category: "Hardware",
    github: "",
    demo: "",
    featured: false,
    details: {
      objective: "Design, build, and program a LEGO Mindstorms EV3 robot for ENED 1002c. The PMR must follow a closed-loop line path, autonomously detect and pick up bins of shredded material, classify them by weight (organic ~25g vs. metal ~125g), and deliver them to the correct drop-off station before returning to start.",
      team: ["Yegor Lushpin", "Baolong Phan — Hardware Lead", "Ethan Myhal", "Andrew Sullivan"],
      bom: [
        { item: "LEGO Mindstorms EV3 Brick", qty: "1", unitCost: "Kit" },
        { item: "Large EV3 Drive Motors", qty: "2", unitCost: "Kit" },
        { item: "Medium EV3 Motor (grab/lift)", qty: "1", unitCost: "Kit" },
        { item: "EV3 Color Sensors", qty: "2", unitCost: "Kit" },
        { item: "EV3 Ultrasonic Sensor", qty: "1", unitCost: "Kit" },
        { item: "EV3 Touch Sensor (E-stop)", qty: "1", unitCost: "Kit" },
      ],
      totalCost: "University-provided LEGO Mindstorms EV3 Education Kit",
      architecture: "Dual color-sensor line following: both white → forward, left black → turn left, right black → turn right. Full state machine in LabVIEW 2016 (single VI): IDLE → SCAN → APPROACH → GRAB → NAVIGATE → DEPOSIT → RETURN → STOP. Weight classification via motor encoder position (Motor Status block) after a timed grab. Gray hairline crossings on the track drive a drop-off counter distinguishing organic (counter=1) vs. metal (counter=2) stations.",
      process: [
        "Defined system requirements and sensor layout as a team in ENED 1002c",
        "Built grab-and-lift mechanism using medium EV3 motor with claw attachment",
        "Implemented dual color-sensor differential steering for line following",
        "Developed weight detection using motor position feedback after a timed lift",
        "Architected state machine inside a single LabVIEW VI with Flat Sequence Structure and shift registers",
        "Calibrated sensor height (~1–1.5 cm from ground, straddling the 1-inch line) to resolve false-positive detections",
        "Conducted structured testing across 7 categories: baseline, speed, sensor sensitivity, turning, error recovery, special features, and endurance",
      ],
      results: "Robot successfully demonstrated autonomous line following, weight-based classification, and bin delivery within the required course layout. All ENED 1002c project requirements met.",
    },
  },
  {
    id: 11,
    title: "ESP32-CAM Smart Flower Pot",
    description: "IoT birthday gift — an ESP32-CAM detects a face, triggers LED animations, and displays personalized messages on an LCD. Fully remote-controllable via a cloud-connected Next.js web dashboard.",
    image: "",
    gallery: [],
    technologies: ["ESP32-CAM", "ESP32-C3", "MQTT", "Next.js", "Face Detection"],
    category: "Personal",
    github: "",
    demo: "",
    featured: false,
    details: {
      objective: "Build a smart flower pot as a birthday gift. An ESP32-CAM detects when a specific person is in frame and triggers LED animations and personalized LCD messages. A cloud-connected web dashboard allows remote message updates and live camera access from anywhere.",
      bom: [
        { item: "ESP32-CAM (AI-Thinker)", qty: "1", unitCost: "$7.99" },
        { item: "ESP32-C3 Super Mini", qty: "1", unitCost: "$4.49" },
        { item: "QAPASS 16×2 I2C LCD Display", qty: "1", unitCost: "$3.99" },
        { item: "5mm Red LEDs", qty: "6", unitCost: "$1.00" },
        { item: "220Ω Resistors", qty: "6", unitCost: "$0.50" },
        { item: "5V 2A USB Power Adapter", qty: "1", unitCost: "$6.99" },
        { item: "PLA Filament (3D-printed pot)", qty: "~100g", unitCost: "$2.00" },
        { item: "Jumper Wires / Connectors", qty: "Assorted", unitCost: "$2.00" },
      ],
      totalCost: "~$29",
      architecture: "Dual-MCU design: ESP32-CAM (AI-Thinker) runs built-in face detection and streams camera feed; ESP32-C3 Super Mini manages 6 LEDs via PWM and drives the I2C LCD. The two MCUs communicate over UART. Both connect to HiveMQ Cloud via MQTT over TLS. A Next.js web dashboard deployed on Vercel allows uploading new messages and selecting LED animation patterns remotely.",
      process: [
        "Defined dual-MCU architecture to offload vision processing from peripheral control",
        "Wrote PlatformIO firmware for ESP32-CAM: face-detection pipeline using built-in ML model + UART TX on detection event",
        "Wrote PlatformIO firmware for ESP32-C3: UART RX handler, LED PWM animations (pulse, wave, sparkle, heartbeat), I2C LCD message display",
        "Integrated MQTT with TLS over HiveMQ Cloud for reliable remote command delivery",
        "Built Next.js + Tailwind web dashboard with preset message slots and LED pattern selector, deployed to Vercel",
        "3D-printed a flower pot enclosure sized to house both PCBs, the LCD, and internal wiring cleanly",
        "Validated full pipeline: face in frame → UART trigger → LED animation + LCD message update",
      ],
      results: "Fully functional gift — face detection reliably triggers LED animation and personalized messages. Remote web dashboard operational for uploading new messages and live camera monitoring.",
    },
  },
];

export const experienceData = [
  {
    id: 0,
    title: "Electrical Engineering Co-op",
    company: "TREW Automation",
    location: "West Chester, Ohio",
    period: "Aug 2026 - Dec 2026",
    description: "Accepted 1st co-op position focused on electrical drawings and design at an automation and controls engineering firm.",
    achievements: [
      "Accepted offer — starting Fall 2026",
      "Focus: electrical drawings, designs, and automation systems",
    ],
    upcoming: true,
  },
  {
    id: 1,
    title: "Electrical Engineering Team Member",
    company: "Bearcats Electric Racing",
    location: "University of Cincinnati",
    period: "Aug 2025 - Present",
    description: "Supporting the design and integration of high-voltage battery systems for a Formula SAE electric race car.",
    achievements: [
      "Won 1st Place (Student Organization category) at CEAS Expo 2026, presented by Marmon Holdings",
      "Designed temperature monitoring system for battery cell thermal validation",
      "Drafted busbar and fusible link drawings for overcurrent protection",
      "Validated fusible link dimensions using oscilloscope measurements",
    ],
  },
  {
    id: 2,
    title: "Junior iOS Developer",
    company: "SunSketcher - Western Kentucky University",
    location: "NASA-supported Project",
    period: "Feb 2024 - Aug 2025",
    description: "Contributed to a NASA-supported citizen science app for photographing solar eclipses.",
    achievements: [
      "Programmed in Swift to configure encrypted backup to servers",
      "Modeled eclipse simulations in MATLAB with NASA engineers",
      "Collaborated with leading heliophysicists on data analysis",
    ],
  },
  {
    id: 3,
    title: "Crew Member",
    company: "Wendy's",
    location: "Alexandria, Kentucky",
    period: "Mar 2025 - Present",
    description: "Providing fast, friendly service in a high-volume restaurant setting.",
    achievements: [
      "Increased feedback survey amount by 125%",
      "Awarded first-ever Employee of the Month at the store",
      "Maintained 97-99% cleanliness score consistently",
    ],
  },
  {
    id: 4,
    title: "Team Leader",
    company: "Technology Student Association",
    location: "Campbell County High School",
    period: "Aug 2023 - May 2025",
    description: "Led a team in Engineering, Coding, and CAD design competitions at regional, state, and national levels.",
    achievements: [
      "Led team through regional, state, and national TSA competitions",
      "Coordinated task assignments, deadlines, and practice sessions",
      "Mentored teammates in competitive STEM environment",
    ],
  },
];

export const navLinks = [
  { name: "About", href: "#about" },
  { name: "Skills", href: "#skills" },
  { name: "Projects", href: "#projects" },
  { name: "Experience", href: "#experience" },
  { name: "Contact", href: "#contact" },
];
